// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQkp8rwqrbH1T4LjVuwGO7ZT_TQnPMPBM',
    appId: '1:581080373754:web:5461e80bef274a2c166c43',
    messagingSenderId: '581080373754',
    projectId: 'geography-geyser-app-cc7f8',
    authDomain: 'geography-geyser-app-cc7f8.firebaseapp.com',
    storageBucket: 'geography-geyser-app-cc7f8.firebasestorage.app',
    measurementId: 'G-CRZEK20BNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX8ka9gfplfmzdSXFD_ixh3ZjXL2ODY0M',
    appId: '1:581080373754:android:eb4a24d017b60820166c43',
    messagingSenderId: '581080373754',
    projectId: 'geography-geyser-app-cc7f8',
    storageBucket: 'geography-geyser-app-cc7f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6C2z0UYTc9Iv0NtLp50ssB5RRsnY9JPQ',
    appId: '1:581080373754:ios:87e22df3ef7445af166c43',
    messagingSenderId: '581080373754',
    projectId: 'geography-geyser-app-cc7f8',
    storageBucket: 'geography-geyser-app-cc7f8.firebasestorage.app',
    iosClientId: '581080373754-ugnbou41i9m5jgtn64umals2mbg0vv3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.wynante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6C2z0UYTc9Iv0NtLp50ssB5RRsnY9JPQ',
    appId: '1:581080373754:ios:87e22df3ef7445af166c43',
    messagingSenderId: '581080373754',
    projectId: 'geography-geyser-app-cc7f8',
    storageBucket: 'geography-geyser-app-cc7f8.firebasestorage.app',
    iosClientId: '581080373754-ugnbou41i9m5jgtn64umals2mbg0vv3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.wynante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQkp8rwqrbH1T4LjVuwGO7ZT_TQnPMPBM',
    appId: '1:581080373754:web:a9647cfe166a305d166c43',
    messagingSenderId: '581080373754',
    projectId: 'geography-geyser-app-cc7f8',
    authDomain: 'geography-geyser-app-cc7f8.firebaseapp.com',
    storageBucket: 'geography-geyser-app-cc7f8.firebasestorage.app',
    measurementId: 'G-TZXHK2ZYYN',
  );
}
